<a href="https://colab.research.google.com/github/2303A51629/B22_1629/blob/main/lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
test_scores = np.random.randint(50, 101, size=(4, 4))
print(test_scores)

[[100  90  73  67]
 [ 53  63  81  99]
 [ 90  58  83  72]
 [ 63  99  92  63]]


In [4]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

Column-wise means: [76.5  77.5  82.25 75.25]
Row-wise means: [82.5  74.   75.75 79.25]


In [5]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 15.341426758942598
Variance: 235.359375


In [6]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 53
Maximum value: 100
Index of minimum value: 4
Index of maximum value: 0


In [7]:
print("Statistical Analysis Summary:")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [82.5  74.   75.75 79.25]
Column-wise means: [76.5  77.5  82.25 75.25]
Overall Standard Deviation: 15.341426758942598
Overall Variance: 235.359375
Global Minimum Value: 53 (Index: 4)
Global Maximum Value: 100 (Index: 0)


In [8]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[103 157 224]
  [111  48 159]
  [140  24  22]]

 [[129 246 135]
  [  9 184 215]
  [ 76  84   1]]

 [[155  62 110]
  [ 33 112  90]
  [237 168 232]]]


In [9]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[103 111 140]
 [129   9  76]
 [155  33 237]]
Green Channel:
 [[157  48  24]
 [246 184  84]
 [ 62 112 168]]
Blue Channel:
 [[224 159  22]
 [135 215   1]
 [110  90 232]]


In [10]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)
print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 110.33333333333333
Average pixel intensity for Green channel: 120.55555555555556
Average pixel intensity for Blue channel: 132.0


In [11]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[153 207 255]
  [161  98 209]
  [190  74  72]]

 [[179 255 185]
  [ 59 234 255]
  [126 134  51]]

 [[205 112 160]
  [ 83 162 140]
  [255 218 255]]]


In [12]:
print("Statistical Analysis Summary:")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[103 111 140]
 [129   9  76]
 [155  33 237]]
Green Channel:
 [[157  48  24]
 [246 184  84]
 [ 62 112 168]]
Blue Channel:
 [[224 159  22]
 [135 215   1]
 [110  90 232]]

Average pixel intensity for Red channel: 110.33333333333333
Average pixel intensity for Green channel: 120.55555555555556
Average pixel intensity for Blue channel: 132.0

Brightened Image (clipped at 255):
 [[[153 207 255]
  [161  98 209]
  [190  74  72]]

 [[179 255 185]
  [ 59 234 255]
  [126 134  51]]

 [[205 112 160]
  [ 83 162 140]
  [255 218 255]]]
